### ISSUE TITLE
Devportal bookmark URL incomplete

### ISSUE THREAD

**Issue by anz-f5** [f5devcentral/f5-agility-labs-nginx#231]
In 'Step 6 - Check the doc pushed by API Team' ( https://clouddocs.f5.com/training/community/nginx/html/class10/module4/lab1/lab1.html ), Click on Developers bookmark. The Developers bookmark itself points to http://dev.sentence.com, which is the default nginx page. The link should be http://dev.sentence.com/devportal .

**Comment by MattDierick** [comment]
@anz-f5 please reach out to me on Teams, because I don't have this issue in the BP. I just deployed it again, and the devportal listens on http://dev.sentence.com.

<img width="1150" alt="Screenshot 2023-01-13 at 10 27 48" src="https://user-images.githubusercontent.com/16579707/212285520-96ccbbb4-aa00-4e56-86d9-93f00cbe6fc3.png">

**Comment by MattDierick** [comment]
I reopen it. On brown field, the upgrade keep the / as root for Devportal. On green field, a brand new DevPortal requires /devportal.

Opening a ticket with engineering

**Comment by MattDierick** [comment]
Engineering working on it.

**Comment by MattDierick** [comment]
Fixed
